import Wrapper from "../layout/wrapper";
import "../styles/index.scss";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        {/* <Wrapper>{children}</Wrapper> */}
        <p>Website under construction</p>
      </body>
    </html>
  );
}
